version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: dockerhub-flask_live_app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      # https://cloud.google.com/docs/authentication/production
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/keyfile.json
    volumes:
      # Inject your specific service account keyfile into the container at runtime.
      - $HOME/.gcp/arte-jr-subber-0f20835848c6.json:/tmp/keys/keyfile.json:ro