apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: arte-jr-subber-deployment
spec:
 selector:
   # Selector for Pods
   app: arte-jr-subber
 ports:
   # Port Map
 - port: 80
   targetPort: 4000
   protocol: TCP
 type: LoadBalancer